# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: そらの忘備録
email: ""
description: >- # this means to ignore newlines until "baseurl:"
    忘備録です。誰かの役に立てばいいな
baseurl: "" # the subpath of your site, e.g. /blog
url: "memorandum.sora81.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sora81dev
github_username:  sora81dev

defaults:
    - scope:
        path: ""
        type: "posts"
      values:
        layout: single
        author_profile: ture
        permalink: "/:title/"

# Build settings
# theme: minima # 消す 
remote_theme: mmistakes/minimal-mistakes@4.27.3
minimal_mistakes_skin: "default" #"air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-feed
  - jekyll-include-cache # 追加

author:
  name: "Mikito Yoshiya"
  avatar: "/assets/img/avatar.png"
  bio: "Software Engineer"
  location: "Tokyo, Japan"
  links:
    - label: "Blog"
      icon: "fas fa-fw fa-link"
      url: "https://mikimemo.hateblo.jp"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mikito0521"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/mikito.yoshiya"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
